name: 'Bug Report'
description: 'Report a bug to help us improve Blackbox CLI'
labels:
  - 'bug'
type: 'Bug'
body:
  - type: 'markdown'
    attributes:
      value: |-
        > [!IMPORTANT]
        > Thanks for taking the time to fill out this bug report!
        >
        > Please search **existing issues** to see if an issue already exists for the bug you encountered.

  - type: 'textarea'
    id: 'problem'
    attributes:
      label: 'What happened?'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true

  - type: 'textarea'
    id: 'expected'
    attributes:
      label: 'What did you expect to happen?'
    validations:
      required: true

  - type: 'textarea'
    id: 'info'
    attributes:
      label: 'Client information'
      description: 'Please paste the full text from the `/about` command. Also include which platform (macOS, Windows, Linux) and which Ollama model you are using.'
      value: |-
        <details>
        <summary>Client Information</summary>

        Run `blackbox` to enter the interactive CLI, then run the `/about` command.

        ```console
        > /about
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: 'textarea'
    id: 'model-info'
    attributes:
      label: 'Model information'
      description: 'Which Ollama model are you using? (e.g., llama3.2, qwen2.5-coder, deepseek-r1)'

  - type: 'textarea'
    id: 'additional-context'
    attributes:
      label: 'Anything else we need to know?'
      description: 'Add any other context about the problem here.'
